name: GitHub Actions Demo

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch: # 添加这一行，表示允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config --global user.email "lmj15979853175@gmail.com"
          git config --global user.name "moyuwuhen601"
      - name: Download file
        run: wget https://raw.githubusercontent.com/hezhijie0327/GFWList2AGH/main/gfwlist2adguardhome/whitelist_full_combine.txt
      - name: Edit file
        run: sed -i 's/https:\/\/dns.opendns.com:443/https:\/\/dns.nextdns.io\/b6983a\/AdGuardHome/g' whitelist_full_combine.txt # 文件名应改为下载的文件名
      - name: Upload file
        run: |
          git add whitelist_full_combine.txt # 文件名应改为下载的文件名
          git commit -m "Updated file"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
