name: GitHub Actions Demo

on:
  push
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download file
        run: wget https://raw.githubusercontent.com/hezhijie0327/GFWList2AGH/main/gfwlist2adguardhome/whitelist_full_combine.txt
      - name: Edit file
        run: sed -i 's/https://dns.opendns.com:443/dns-query/https://dns.nextdns.io/b6983a/AdGuardHome/g' file.txt
      - name: Upload file
        run: |
          git add file.txt
          git commit -m "Updated file"
          git push
